# Generated by Django 5.0.6 on 2024-06-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historiqueConsultations', models.TextField()),
                ('traitementsEnCours', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('medicaments', models.TextField()),
                ('dosage', models.TextField()),
                ('instructions', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateHeure', models.DateTimeField()),
                ('statut', models.CharField(max_length=50)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateVisite', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('dossierPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.dossierpatient')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
    ]
