# Generated by Django 5.0.6 on 2024-06-30 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_patient_created_at_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='symptome',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
