# Generated by Django 5.0.6 on 2024-06-30 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rendezvous_symptome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierpatient',
            name='historiqueConsultations',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.medecin'),
        ),
    ]
