# Generated by Django 5.0.6 on 2024-07-01 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_dossierpatient_historiqueconsultations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='licence',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
