# Generated by Django 5.0.6 on 2024-07-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_medecin_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='dossierPatient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.dossierpatient'),
        ),
    ]
