# Generated by Django 5.0.6 on 2024-07-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_prescription_checking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='checking',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
